name: CI

on:
  push:
    branches: [ main, 'feature/**', 'hotfix/**' ]
  pull_request:
    branches: [ main, 'feature/**', 'hotfix/**' ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --only-verified
        
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      continue-on-error: true
      with:
        version: latest
        skip-cache: true
